### ISSUE TITLE
Drake goes Quack.

### ISSUE THREAD

**Issue by jeanmilali** [Stevester118/NPC-Overhead-Dialogue#2]
I was figthing drakes in the Kebos volcano and the drakes could not stop yelling Quack... I do not think that this is the sound they are supposed to make.

**Comment by SteveDevGit** [comment]
You are absolutely correct. The reason they are doing that is because the "Quack" sound effect was meant for the duck version of  'drakes', but the plugin checks for NPC name and not ID. I will roll out a fix for this soon.

**Comment by jeanmilali** [comment]
I can confirm that it is now fixed ! But what the hell do you mean by the "duck version of drakes"?? lmao
