### ISSUE TITLE
No longer works properly after game update.

### ISSUE THREAD

**Issue by misslovesyoulots** [Stevester118/NPC-Overhead-Dialogue#4]
Ever since the game update a while ago, this plugin does not work correctly anymore.

During dialog with an NPC, their dialog appears above their head just fine. However, when it comes turn for your playable character to speak, it only ever comes up as "Click to continue" or "Please wait..." above your head.

Restarting the client/plugin does not work, & I have checked for incompatible plugins. 

Pweasee fix dis because I like dis plugin a lot but it no work no more :(

**Comment by SteveDevGit** [comment]
fixed in https://github.com/Stevester118/NPC-Overhead-Dialogue/commit/e3944514a38e2313ab23ff8083542d1359327c69
